const territoriesArray = [
  "Alaska",
  "Northwest Territory",
  "Greenland",
  "Alberta",
  "Ontario",
  "Quebec",
  "Western United States",
  "Eastern United States",
  "Central America",
  "Venezuela",
  "Peru",
  "Brazil",
  "Argentina",
  "North Africa",
  "Egypt",
  "East Africa",
  "Congo",
  "South Africa",
  "Madagascar",
  "Iceland",
  "Scandinavia",
  "Ukraine",
  "Great Britian",
  "Northern Europe",
  "Southern Europe",
  "Western Europe",
  "Indonesia",
  "New Guinea",
  "Western Australia",
  "Eastern Australia",
  "Siam",
  "India",
  "China",
  "Mongolia",
  "Japan",
  "Irkutsk",
  "Yakutsk",
  "Kamchatka",
  "Siberia",
  "Afghanistan",
  "Ural",
  "Middle East",
];

export default territoriesArray;
